# --- Configurações do PostgreSQL ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.jdbc.url=jdbc:postgresql://dbecclesia.c8j0akkki2g6.us-east-1.rds.amazonaws.com:5432/dbEcclesia
#quarkus.datasource.username=postgres
#quarkus.datasource.password=Qwaszx123!

# Atualizar o banco automaticamente (equivalente ao ddl-auto=update)
quarkus.hibernate-orm.database.generation=update

# Exibir logs do SQL
quarkus.hibernate-orm.log.sql=false

# --- InfinitePay Configs ---
infinitepay-api.url=https://api.infinitepay.io/invoices/public/checkout/links
infinitepay.token=SEU_TOKEN_DE_PRODUCAO_AQUI
infinitepay.handle=harison-nunes
infinitepay.redirect-base=${FRONTEND_URL}
infinitepay.webhook-url=${WEBHOOK_URL}


# --- Configurações do JWT ---
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=auth-api
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# Garante que o Quarkus saiba onde ler as permissões (Admin, Líder) dentro do token
smallrye.jwt.path.groups=groups

# --- REGRAS DE ACESSO (Segurança Blindada) ---

# 1. PASSE LIVRE PARA O CORS (PREFLIGHT)
# Tem que ser /api/* para ter força suficiente para vencer a regra de bloqueio!
quarkus.http.auth.permission.cors.paths=/api/*
quarkus.http.auth.permission.cors.policy=permit
quarkus.http.auth.permission.cors.methods=OPTIONS

# 2. ROTAS PÚBLICAS REAIS (Apenas o estritamente necessário sem login)
quarkus.http.auth.permission.public.paths=/api/auth/*,/api/webhooks/*,/api/public/*
quarkus.http.auth.permission.public.policy=permit

# 3. BLOQUEIO GLOBAL (Tudo que não for público, EXIGE token)
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated


# --- OBSERVABILIDADE E LOGS ---
# Formata o SQL do Hibernate para ficar indentado e fácil de ler (já que o log.sql=true está ativo)
quarkus.hibernate-orm.log.format-sql=true

# Habilita o log de acesso HTTP (Mostra as requisições que chegam do React)
quarkus.http.access-log.enabled=true
# Usa um padrão de log mais descritivo
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b "%{i,Referer}" "%{i,User-Agent}" "%{X-Forwarded-For}i"


