# --- Configurações do PostgreSQL ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.jdbc.url=jdbc:postgresql://dbecclesia.c8j0akkki2g6.us-east-1.rds.amazonaws.com:5432/dbEcclesia
#quarkus.datasource.username=postgres
#quarkus.datasource.password=Qwaszx123!

# Atualizar o banco automaticamente (equivalente ao ddl-auto=update)
quarkus.hibernate-orm.database.generation=update

# Exibir logs do SQL
quarkus.hibernate-orm.log.sql=false

# --- InfinitePay Configs ---
infinitepay-api.url=https://api.infinitepay.io/invoices/public/checkout/links
infinitepay.token=SEU_TOKEN_DE_PRODUCAO_AQUI
infinitepay.handle=harison-nunes
infinitepay.redirect-base=${FRONTEND_URL}
infinitepay.webhook-url=${WEBHOOK_URL}


# --- Configurações do JWT ---
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=auth-api
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem


# Garante que o Quarkus saiba onde ler as permissões (Admin, Líder) dentro do token
smallrye.jwt.path.groups=groups

# ==========================================
# 1. DESATIVA CORS NATIVO (Vamos usar o CorsFilter.java)
# ==========================================
quarkus.http.cors=false

# ==========================================
# 2. REGRAS DE ACESSO (Segurança Blindada)
# ==========================================
# PRIORIDADE 3: Liberação absoluta do OPTIONS para o seu CorsFilter.java funcionar
quarkus.http.auth.permission.cors.paths=/api/*
quarkus.http.auth.permission.cors.policy=permit
quarkus.http.auth.permission.cors.methods=OPTIONS
quarkus.http.auth.permission.cors.priority=3

# PRIORIDADE 2: Rotas Públicas (Igrejas, Auth, Webhooks)
quarkus.http.auth.permission.public.paths=/api/auth/*,/api/webhooks/*,/api/*/publico/*,/api/igrejas,/api/igrejas/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.public.priority=2

# PRIORIDADE 1: Bloqueio Global (O resto exige token)
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.authenticated.priority=1


# --- OBSERVABILIDADE E LOGS ---
# Formata o SQL do Hibernate para ficar indentado e fácil de ler (já que o log.sql=true está ativo)
quarkus.hibernate-orm.log.format-sql=true

# Habilita o log de acesso HTTP (Mostra as requisições que chegam do React)
quarkus.http.access-log.enabled=true
# Usa um padrão de log mais descritivo
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b "%{i,Referer}" "%{i,User-Agent}" "%{X-Forwarded-For}i"


